repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    -   id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
    -   id: ruff-format
        types_or: [ python, pyi ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
