version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./mlmodels:/app/mlmodels
      - ./mlreports:/app/mlreports
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - PYTHON_VERSION=3.12
    env_file:
      - .env
    restart: unless-stopped
