data:
  processed_data: data/new_processed_data.json
  reference_data: data/referance_rooms-1737378184366.csv
  supplier_data: data/updated_core_rooms.csv
  vectorizer: data/vectorizer.pkl
  data_folder: data/
feature_type: numeric_feature
log_level: INFO
model_configs:
  xgb:
    fixed_params:
      apply_imbalance: false
      eval_metric: logloss
      standard_scaler: true
      threshold: 0.9
    model_name: xgb
    model_path: mlmodels/xgb_model.json
    model_type: xgboost
    report_path: mlreports
    search_params:
      colsample_bytree:
      - 0.7962979498154026
      gamma:
      - 0.07407655998633511
      learning_rate:
      - 0.02053083889963104
      max_depth:
      - 8
      min_child_weight:
      - 3
      n_estimators:
      - 300
      reg_alpha:
      - 0.3100421704998185
      reg_lambda:
      - 0.34097532561863875
      subsample:
      - 0.7093174872587061
random_state: 42
sentence_transformer_model: all-MiniLM-L6-v2
test_size: 0.2
